### ISSUE TITLE
Crash when deleting rules from index

### ISSUE THREAD

**Issue by SerialVelocity** [squat/kilo#22]
Stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10985f3]

goroutine 11 [running]:
github.com/squat/kilo/pkg/iptables.deleteFromIndex(0x0, 0xc00051dee0, 0xc00051ded8, 0xc0003660c0)
	/kilo/pkg/iptables/iptables.go:226 +0x93
github.com/squat/kilo/pkg/iptables.(*Controller).CleanUp(0xc00051dec0, 0x0, 0x0)
	/kilo/pkg/iptables/iptables.go:265 +0x83
github.com/squat/kilo/pkg/mesh.(*Mesh).cleanUp(0xc0002066e0)
	/kilo/pkg/mesh/mesh.go:708 +0x47
panic(0x138a7a0, 0x26d5c10)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/squat/kilo/pkg/iptables.(*Controller).Set(0xc00051dec0, 0xc000232f00, 0x13, 0x14, 0x0, 0x0)
	/kilo/pkg/iptables/iptables.go:243 +0x364
github.com/squat/kilo/pkg/mesh.(*Mesh).applyTopology(0xc0002066e0)
	/kilo/pkg/mesh/mesh.go:635 +0x12e0
github.com/squat/kilo/pkg/mesh.(*Mesh).syncNodes(0xc0002066e0, 0xc00032bc40)
	/kilo/pkg/mesh/mesh.go:445 +0x751
github.com/squat/kilo/pkg/mesh.(*Mesh).Run(0xc0002066e0, 0x0, 0x0)
	/kilo/pkg/mesh/mesh.go:350 +0x735
main.Main.func4(0x0, 0x0)
	/kilo/cmd/kg/main.go:218 +0x168
github.com/oklog/run.(*Group).Run.func1(0xc0000a8300, 0xc0003d1220, 0xc000414c30)
	/kilo/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/oklog/run.(*Group).Run
	/kilo/vendor/github.com/oklog/run/group.go:37 +0xbe
```

Looks like this is wrong:
https://github.com/squat/kilo/blob/3facc9f34f7f6d645b7508528ae4ca45afcd6c93/pkg/iptables/iptables.go#L225-L230

I think `(*rules)[j]` should be `(*rules)[i+j]`. You've got this in multiple places in the file. It might be worth switching to a standard for loop to make it a little clearer.

**Comment by squat** [comment]
Yes you’re completely right :)
