### ISSUE TITLE
Kilo panicking when iptables fails

### ISSUE THREAD

**Issue by SerialVelocity** [squat/kilo#51]
Here's the stacktrace:
```
{"caller":"mesh.go:617","component":"kilo","error":"failed to delete rule: failed to clear iptables chain: running [/sbin/iptables -t filter -F KILO-IPIP --wait]: exit status 4: iptables: Resource temporarily unavailable.\n","level":"error","ts":"2020-04-19T18:33:48.316238028Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x104fe51]

goroutine 42 [running]:
github.com/squat/kilo/pkg/iptables.(*Controller).reconcile(0xc00011b810, 0x0, 0x0)
	/kilo/pkg/iptables/iptables.go:246 +0xe1
github.com/squat/kilo/pkg/iptables.(*Controller).Run.func1(0xc00011b810, 0xc000088180)
	/kilo/pkg/iptables/iptables.go:230 +0x11f
created by github.com/squat/kilo/pkg/iptables.(*Controller).Run
	/kilo/pkg/iptables/iptables.go:222 +0xc3
```

**Comment by squat** [comment]
@SerialVelocity thanks for reporting this :) after some thinking, I found the offending code and fixed it in 9b19bbe69c1528ed5a81a9edbe0c9ef4a9b489af
